apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: kubernetes-actions-run
spec:
  serviceAccountName: kubernetes-actions-account
  taskRef:
    name: kubernetes-actions
  params:
    - name: script
      value: |
        kubectl apply -f https://github.com/abhishakeonteddu/gitopps_repo/blob/main/charts/helm-example/deployment.yaml -n tekton-demo
        echo "---------"
        kubectl get deploy
