apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
spec:
  resources:
    kubernetesResource:
      serviceType: LoadBalancer
  triggers:
    - name: github-listener
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["push"]
#        - name: "only when PRs are opened"
#          ref:
#            name: "cel"
#          params:
#            - name: "filter"
              # value: "body.action in ['opened', 'synchronize', 'reopened']"
#              value: body.ref == 'refs/heads/trigger-config'
      bindings:
        - ref: tekton-trigger-binding
      template:
        ref: tekton-trigger-template
        
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: service-tekton-triggers-sa
            containers:
              - resources:
                  requests:
                    memory: "64Mi"
                    cpu: "250m"
                  limits:
                    memory: "128Mi"
                    cpu: "500m"
