apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
stringData:
  credentials: |-
    [default]
    aws_access_key_id     = AKIAWOM5BCBYKHQL5OUW
    aws_secret_access_key = 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
  config: |-
    [profile $(profile-name)]
    region = us-east-1
    output = text
    [default]
    region = us-east-2
