---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipeline
  namespace: tekton-demo
secrets:
  - name: git-ssh-key
  - name: awsregcred
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-pipeline
rules:
  # Core API
  - apiGroups: [""]
    resources: ["services", "pods", "deployments", "configmaps", "secrets"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  # Apps API
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "jobs"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  # Tekton API
  - apiGroups: ["tekton.dev"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-pipeline
subjects:
  - kind: ServiceAccount
    name: tekton-pipeline
    namespace: tekton-demo
roleRef:
  kind: ClusterRole
  name: tekton-pipeline
  apiGroup: rbac.authorization.k8s.io
